module.export = {
    properties: [{
        id: 1,
        name: "align-content",
        camelCased: "alignContent",
        valueType: "oneOf",
        values: ["flex-start", "flex-end", "center", "stretch", "space-between", "space-around"]
    }, {
        id: 2,
        name: "align-items",
        camelCased: "alignItems",
        valueType: "oneOf",
        values: ["flex-start", "flex-end", "center", "stretch", "baseline"]
    }, {
        id: 3,
        name: "align-self",
        camelCased: "alignSelf",
        valueType: "oneOf",
        values: ["auto", "flex-start", "flex-end", "center", "baseline"]
    }, {
        id: 4,
        name: "aspect-ratio",
        camelCased: "aspectRatio",
        valueType: "number"
    }, {
        id: 5,
        name: "border-bottom-width",
        camelCased: "borderBottomWidth",
        valueType: "number"
    }, {
        id: 6,
        name: "border-left-width",
        camelCased: "borderLeftWidth",
        valueType: "number"
    }, {
        id: 7,
        name: "border-right-width",
        camelCased: "borderRightWidth",
        valueType: "number"
    }, {
        id: 8,
        name: "border-top-width",
        camelCased: "borderTopWidth",
        valueType: "number"
    }, {
        id: 9,
        name: "border-end-width",
        camelCased: "borderEndWidth",
        valueType: "number"
    }, {
        id: 10,
        name: "border-start-width",
        camelCased: "borderStartWidth",
        valueType: "number"
    }, {
        id: 11,
        name: "border-width",
        camelCased: "borderWidth",
        valueType: "number"
    }, {
        id: 12,
        name: "bottom",
        camelCased: "bottom",
        valueType: "number"
    }, {
        id: 13,
        name: "direction",
        camelCased: "direction",
        valueType: "oneOf",
        values: ["inherit", "ltr", "rtl"]
    }, {
        id: 14,
        name: "display",
        camelCased: "display",
        valueType: "oneOf",
        values: ["none", "flex"]
    }, {
        id: 15,
        name: "end",
        camelCased: "end",
        valueType: "number"
    }, {
        id: 16,
        name: "start",
        camelCased: "start",
        valueType: "number"
    }, {
        id: 17,
        name: "flex",
        camelCased: "flex",
        valueType: "number"
    }, {
        id: 18,
        name: "flex-direction",
        camelCased: "flexDirection",
        valueType: "oneOf",
        values: ["row", "row-reverse", "column", "column-reverse"]
    }, {
        id: 19,
        name: "flex-basis",
        camelCased: "flexBasis",
        valueType: "number"
    }, {
        id: 20,
        name: "flex-grow",
        camelCased: "flexGrow",
        valueType: "number"
    }, {
        id: 21,
        name: "flex-shrink",
        camelCased: "flexShrink",
        valueType: "number"
    }, {
        id: 21,
        name: "flex-wrap",
        camelCased: "flexWrap",
        valueType: "oneOf",
        values: ["wrap", "nowrap"]
    }, {
        id: 22,
        name: "height",
        camelCased: "height",
        valueType: "number"
    }, {
        id: 23,
        name: "justify-content",
        camelCased: "justifyContent",
        valueType: "oneOf",
        values: ["flex-start", "flex-end", "center", "space-between", "space-around"]
    }, {
        id: 24,
        name: "left",
        camelCased: "left",
        valueType: "number"
    }, {
        id: 25,
        name: "margin",
        camelCased: "margin",
        valueType: "number"
    }, {
        id: 26,
        name: "margin-bottom",
        camelCased: "marginBottom",
        valueType: "number"
    }, {
        id: 27,
        name: "margin-horizontal",
        camelCased: "marginHorizontal",
        valueType: "number"
    }, {
        id: 28,
        name: "margin-left",
        camelCased: "marginLeft",
        valueType: "number"
    }, {
        id: 29,
        name: "margin-right",
        camelCased: "marginRight",
        valueType: "number"
    }, {
        id: 30,
        name: "margin-top",
        camelCased: "marginTop",
        valueType: "number"
    }, {
        id: 31,
        name: "marginVertical",
        camelCased: "marginVertical",
        valueType: "number"
    }, {
        id: 32,
        name: "margin-end",
        camelCased: "marginEnd",
        valueType: "number"
    }, {
        id: 33,
        name: "margin-start",
        camelCased: "marginStart",
        valueType: "number"
    }, {
        id: 34,
        name: "max-height",
        camelCased: "maxHeight",
        valueType: "number"
    }, {
        id: 35,
        name: "max-width",
        camelCased: "maxWidth",
        valueType: "number"
    }, {
        id: 36,
        name: "min-height",
        camelCased: "minHeight",
        valueType: "number"
    }, {
        id: 37,
        name: "min-width",
        camelCased: "minWidth",
        valueType: "number"
    }, {
        id: 38,
        name: "padding",
        camelCased: "padding",
        valueType: "number"
    }, {
        id: 39,
        name: "padding-bottom",
        camelCased: "paddingBottom",
        valueType: "number"
    }, {
        id: 40,
        name: "padding-horizontal",
        camelCased: "paddingHorizontal",
        valueType: "number"
    }, {
        id: 41,
        name: "padding-left",
        camelCased: "paddingLeft",
        valueType: "number"
    }, {
        id: 42,
        name: "padding-right",
        camelCased: "paddingRight",
        valueType: "number"
    }, {
        id: 43,
        name: "padding-top",
        camelCased: "paddingTop",
        valueType: "number"
    }, {
        id: 44,
        name: "padding-vertical",
        camelCased: "paddingVertical",
        valueType: "number"
    }, {
        id: 46,
        name: "padding-end",
        camelCased: "paddingEnd",
        valueType: "number"
    }, {
        id: 47,
        name: "padding-start",
        camelCased: "paddingStart",
        valueType: "number"
    }, {
        id: 48,
        name: "position",
        camelCased: "position",
        valueType: "oneOf",
        values: ["absolute", "relative"]
    }, {
        id: 49,
        name: "right",
        camelCased: "right",
        valueType: "number"
    }, {
        id: 49,
        name: "top",
        camelCased: "top",
        valueType: "number"
    }, {
        id: 50,
        name: "width",
        camelCased: "width",
        valueType: "number"
    }, {
        id: 51,
        name: "zIndex",
        camelCased: "zIndex",
        valueType: "number"
    }, { // *need to check
        id: 52,
        name: "shadow-color",
        camelCased: "shadowColor",
        valueType: "string"
    }, { // *need to check
        id: 53,
        name: "shadow-offset",
        camelCased: "shadowOffset",
        valueType: "string"
    }, { // *need to check
        id: 54,
        name: "shadow-opacity",
        camelCased: "shadowOpacity",
        valueType: "number"
    }, { // *need to check
        id: 55,
        name: "shadow-radius",
        camelCased: "shadowRadius",
        valueType: "number"
    }, {
        id: 56,
        name: "transform",
        camelCased: "transform",
        valueType: "string"
    }, {
        id: 57,
        name: "backface-visibility",
        camelCased: "backfaceVisibility",
        valueType: "oneOf",
        values: ["visible", "hidden"]
    }, {
        id: 58,
        name: "background-color",
        camelCased: "backgroundColor",
        valueType: "string"
    }, {
        id: 59,
        name: "border-bottom-left-radius",
        camelCased: "borderBottomLeftRadius",
        valueType: "number"
    }, {
        id: 60,
        name: "border-bottom-right-radius",
        camelCased: "borderBottomRightRadius",
        valueType: "number"
    }, {
        id: 61,
        name: "border-color",
        camelCased: "borderColor",
        valueType: "string"
    }, {
        id: 62,
        name: "border-radius",
        camelCased: "borderRadius",
        valueType: "number"
    }, {
        id: 63,
        name: "border-top-left-radius",
        camelCased: "borderTopLeftRadius",
        valueType: "number"
    }, {
        id: 64,
        name: "border-top-right-radius",
        camelCased: "borderTopRightRadius",
        valueType: "number"
    }, {
        id: 65,
        name: "border-width",
        camelCased: "borderWidth",
        valueType: "number"
    }, {
        id: 66,
        name: "opacity",
        camelCased: "opacity",
        valueType: "number"
    }, {
        id: 67,
        name: "overflow",
        camelCased: "overflow",
        valueType: "oneOf",
        values: ["visible", "hidden"]
    }, {
        id: 68,
        name: "resize-mode",
        camelCased: "resizeMode",
        valueType: "oneOf",
        values: ["cover", "contain", "stretch", "repeat", "center"]
    }, {
        id: 69,
        name: "tint-color",
        camelCased: "tintColor",
        valueType: "string"
    }, {
        id: 70,
        name: "overlay-color",
        camelCased: "overlay-color",
        valueType: "string"
    }]
}